baseURL = "http://localhost:1313"
canonifyURLs = true
relativeURLs = false

# Taxonomy URL slug: remove Vietnamese accents and slugify
disablePathToLower = false
preserveTaxonomyNames = false
removePathAccents = true