baseURL = "http://localhost:1313/"
languageCode = "vi-vn"
title = "Tùng Blog"
theme = "PaperMod"

enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  ShowBreadCrumbs = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  defaultTheme = "light"
  description = "Blog hướng dẫn AI, SEO, tự động hóa, Hugo & kiếm tiền online 2026."

# ----- Navigation Menu -------------------
[outputs]
  home = ["HTML", "RSS", "JSON"]

# ----- Minify ----------------------------
[minify]
  disableXML = true
  minifyOutput = true
  
[menu]
  [[menu.main]]
    name = "Tìm kiếm"
    url = "/search"
    weight = 1

  [[menu.main]]
    name = "Danh mục"
    url = "/categories"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 3

  [[menu.main]]
    name = "Liên hệ"
    url = "https://tungblog.example/contact"
    weight = 4


