baseURL = "https://tungltdev.github.io/hugo_myblog"
canonifyURLs = true
relativeURLs = false

# Taxonomy URL slug: remove Vietnamese accents and slugify
disablePathToLower = false
preserveTaxonomyNames = false
removePathAccents = true